/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	autoscalingxk8siov1beta1 "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/autoscaling.x-k8s.io/v1beta1"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AutoscalingLimitRangeLister helps list AutoscalingLimitRanges.
// All objects returned here must be treated as read-only.
type AutoscalingLimitRangeLister interface {
	// List lists all AutoscalingLimitRanges in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingxk8siov1beta1.AutoscalingLimitRange, err error)
	// AutoscalingLimitRanges returns an object that can list and get AutoscalingLimitRanges.
	AutoscalingLimitRanges(namespace string) AutoscalingLimitRangeNamespaceLister
	AutoscalingLimitRangeListerExpansion
}

// autoscalingLimitRangeLister implements the AutoscalingLimitRangeLister interface.
type autoscalingLimitRangeLister struct {
	listers.ResourceIndexer[*autoscalingxk8siov1beta1.AutoscalingLimitRange]
}

// NewAutoscalingLimitRangeLister returns a new AutoscalingLimitRangeLister.
func NewAutoscalingLimitRangeLister(indexer cache.Indexer) AutoscalingLimitRangeLister {
	return &autoscalingLimitRangeLister{listers.New[*autoscalingxk8siov1beta1.AutoscalingLimitRange](indexer, autoscalingxk8siov1beta1.Resource("autoscalinglimitrange"))}
}

// AutoscalingLimitRanges returns an object that can list and get AutoscalingLimitRanges.
func (s *autoscalingLimitRangeLister) AutoscalingLimitRanges(namespace string) AutoscalingLimitRangeNamespaceLister {
	return autoscalingLimitRangeNamespaceLister{listers.NewNamespaced[*autoscalingxk8siov1beta1.AutoscalingLimitRange](s.ResourceIndexer, namespace)}
}

// AutoscalingLimitRangeNamespaceLister helps list and get AutoscalingLimitRanges.
// All objects returned here must be treated as read-only.
type AutoscalingLimitRangeNamespaceLister interface {
	// List lists all AutoscalingLimitRanges in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingxk8siov1beta1.AutoscalingLimitRange, err error)
	// Get retrieves the AutoscalingLimitRange from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingxk8siov1beta1.AutoscalingLimitRange, error)
	AutoscalingLimitRangeNamespaceListerExpansion
}

// autoscalingLimitRangeNamespaceLister implements the AutoscalingLimitRangeNamespaceLister
// interface.
type autoscalingLimitRangeNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingxk8siov1beta1.AutoscalingLimitRange]
}
