/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	autoscalingxk8siov1beta1 "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/autoscaling.x-k8s.io/v1beta1"
	applyconfigurationautoscalingxk8siov1beta1 "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/client/applyconfiguration/autoscaling.x-k8s.io/v1beta1"
	scheme "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/client/clientset/versioned/scheme"
	gentype "k8s.io/client-go/gentype"
)

// AutoscalingLimitRangesGetter has a method to return a AutoscalingLimitRangeInterface.
// A group's client should implement this interface.
type AutoscalingLimitRangesGetter interface {
	AutoscalingLimitRanges(namespace string) AutoscalingLimitRangeInterface
}

// AutoscalingLimitRangeInterface has methods to work with AutoscalingLimitRange resources.
type AutoscalingLimitRangeInterface interface {
	Create(ctx context.Context, autoscalingLimitRange *autoscalingxk8siov1beta1.AutoscalingLimitRange, opts v1.CreateOptions) (*autoscalingxk8siov1beta1.AutoscalingLimitRange, error)
	Update(ctx context.Context, autoscalingLimitRange *autoscalingxk8siov1beta1.AutoscalingLimitRange, opts v1.UpdateOptions) (*autoscalingxk8siov1beta1.AutoscalingLimitRange, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, autoscalingLimitRange *autoscalingxk8siov1beta1.AutoscalingLimitRange, opts v1.UpdateOptions) (*autoscalingxk8siov1beta1.AutoscalingLimitRange, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingxk8siov1beta1.AutoscalingLimitRange, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingxk8siov1beta1.AutoscalingLimitRangeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingxk8siov1beta1.AutoscalingLimitRange, err error)
	Apply(ctx context.Context, autoscalingLimitRange *applyconfigurationautoscalingxk8siov1beta1.AutoscalingLimitRangeApplyConfiguration, opts v1.ApplyOptions) (result *autoscalingxk8siov1beta1.AutoscalingLimitRange, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, autoscalingLimitRange *applyconfigurationautoscalingxk8siov1beta1.AutoscalingLimitRangeApplyConfiguration, opts v1.ApplyOptions) (result *autoscalingxk8siov1beta1.AutoscalingLimitRange, err error)
	AutoscalingLimitRangeExpansion
}

// autoscalingLimitRanges implements AutoscalingLimitRangeInterface
type autoscalingLimitRanges struct {
	*gentype.ClientWithListAndApply[*autoscalingxk8siov1beta1.AutoscalingLimitRange, *autoscalingxk8siov1beta1.AutoscalingLimitRangeList, *applyconfigurationautoscalingxk8siov1beta1.AutoscalingLimitRangeApplyConfiguration]
}

// newAutoscalingLimitRanges returns a AutoscalingLimitRanges
func newAutoscalingLimitRanges(c *AutoscalingV1beta1Client, namespace string) *autoscalingLimitRanges {
	return &autoscalingLimitRanges{
		gentype.NewClientWithListAndApply[*autoscalingxk8siov1beta1.AutoscalingLimitRange, *autoscalingxk8siov1beta1.AutoscalingLimitRangeList, *applyconfigurationautoscalingxk8siov1beta1.AutoscalingLimitRangeApplyConfiguration](
			"autoscalinglimitranges",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *autoscalingxk8siov1beta1.AutoscalingLimitRange {
				return &autoscalingxk8siov1beta1.AutoscalingLimitRange{}
			},
			func() *autoscalingxk8siov1beta1.AutoscalingLimitRangeList {
				return &autoscalingxk8siov1beta1.AutoscalingLimitRangeList{}
			},
		),
	}
}
