/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	autoscalinglimitrangeautoscalingxk8siov1beta1 "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/autoscaling.x-k8s.io/v1beta1"
	versioned "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/client/clientset/versioned"
	internalinterfaces "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/client/informers/externalversions/internalinterfaces"
	autoscalingxk8siov1beta1 "k8s.io/autoscaler/cluster-autoscaler/apis/autoscalinglimitrange/client/listers/autoscaling.x-k8s.io/v1beta1"
	cache "k8s.io/client-go/tools/cache"
)

// AutoscalingLimitRangeInformer provides access to a shared informer and lister for
// AutoscalingLimitRanges.
type AutoscalingLimitRangeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() autoscalingxk8siov1beta1.AutoscalingLimitRangeLister
}

type autoscalingLimitRangeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAutoscalingLimitRangeInformer constructs a new informer for AutoscalingLimitRange type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAutoscalingLimitRangeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAutoscalingLimitRangeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAutoscalingLimitRangeInformer constructs a new informer for AutoscalingLimitRange type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAutoscalingLimitRangeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutoscalingV1beta1().AutoscalingLimitRanges(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutoscalingV1beta1().AutoscalingLimitRanges(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutoscalingV1beta1().AutoscalingLimitRanges(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutoscalingV1beta1().AutoscalingLimitRanges(namespace).Watch(ctx, options)
			},
		},
		&autoscalinglimitrangeautoscalingxk8siov1beta1.AutoscalingLimitRange{},
		resyncPeriod,
		indexers,
	)
}

func (f *autoscalingLimitRangeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAutoscalingLimitRangeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *autoscalingLimitRangeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&autoscalinglimitrangeautoscalingxk8siov1beta1.AutoscalingLimitRange{}, f.defaultInformer)
}

func (f *autoscalingLimitRangeInformer) Lister() autoscalingxk8siov1beta1.AutoscalingLimitRangeLister {
	return autoscalingxk8siov1beta1.NewAutoscalingLimitRangeLister(f.Informer().GetIndexer())
}
