/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AutoscalingLimitRangeSpecApplyConfiguration represents a declarative configuration of the AutoscalingLimitRangeSpec type for use
// with apply.
type AutoscalingLimitRangeSpecApplyConfiguration struct {
	Limits        *LimitRangeApplyConfiguration `json:"limits,omitempty"`
	ScopeSelector map[string]string             `json:"scopeSelector,omitempty"`
}

// AutoscalingLimitRangeSpecApplyConfiguration constructs a declarative configuration of the AutoscalingLimitRangeSpec type for use with
// apply.
func AutoscalingLimitRangeSpec() *AutoscalingLimitRangeSpecApplyConfiguration {
	return &AutoscalingLimitRangeSpecApplyConfiguration{}
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *AutoscalingLimitRangeSpecApplyConfiguration) WithLimits(value *LimitRangeApplyConfiguration) *AutoscalingLimitRangeSpecApplyConfiguration {
	b.Limits = value
	return b
}

// WithScopeSelector puts the entries into the ScopeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ScopeSelector field,
// overwriting an existing map entries in ScopeSelector field with the same key.
func (b *AutoscalingLimitRangeSpecApplyConfiguration) WithScopeSelector(entries map[string]string) *AutoscalingLimitRangeSpecApplyConfiguration {
	if b.ScopeSelector == nil && len(entries) > 0 {
		b.ScopeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ScopeSelector[k] = v
	}
	return b
}
